-- CREATE schema if not exists iot;

-- create virtual warehouse
CREATE OR REPLACE WAREHOUSE md_test_wh
WAREHOUSE_SIZE=XSMALL
AUTO_SUSPEND = 60
INITIALLY_SUSPENDED=TRUE;

-- create objects
-- log:
  -- 2025-07-11 add field: SENSOR_TEST & SENSOR_12
CREATE or ALTER TABLE RAW_IOT (
	SENSOR_ID NUMBER(6,0),
	SENSOR_0 NUMBER(6,2),
	SENSOR_TEST NUMBER(6,2),
	SENSOR_1 NUMBER(6,2),
	SENSOR_2 NUMBER(6,2),
	SENSOR_3 NUMBER(6,2),
	SENSOR_4 NUMBER(6,2),
	SENSOR_5 NUMBER(6,2),
	SENSOR_6 NUMBER(6,2),
	SENSOR_7 NUMBER(6,2),
	SENSOR_8 NUMBER(6,2),
	SENSOR_9 NUMBER(6,2),
	SENSOR_10 NUMBER(6,2),
	SENSOR_11 NUMBER(6,2),
	SENSOR_12 NUMBER(6,2)
);

CREATE OR REPLACE VIEW RAW_IOT_TEST;

CREATE OR REPLACE VIEW
SELECT SENSOR_ID, SENSOR_0 AS total_spent
FROM customer
GROUP BY SENSOR_ID
ORDER BY SENSOR_ID DESC;
