-- context:
SELECT
  CURRENT_DATABASE() AS database_name,
  CURRENT_SCHEMA() AS schema_name,
  CURRENT_USER() AS current_user,
  CURRENT_ROLE() AS current_role;


-- CREATE schema if not exists iot;

-- create virtual warehouse
CREATE OR REPLACE WAREHOUSE md_test_wh_1
WAREHOUSE_SIZE=XSMALL
AUTO_SUSPEND = 60
INITIALLY_SUSPENDED=TRUE;

ALTER TABLE RAW_IOT ADD COLUMN SENSOR_TEST STRING;

-- create objects
-- log:
  -- 2025-07-11 add field: SENSOR_TEST & SENSOR_12
-- CREATE or ALTER TABLE RAW_IOT (
-- 	SENSOR_ID NUMBER(6,0),
-- 	SENSOR_0 NUMBER(6,2),
-- 	SENSOR_TEST NUMBER(6,2),
-- 	SENSOR_1 NUMBER(6,2),
-- 	SENSOR_2 NUMBER(6,2),
-- 	SENSOR_3 NUMBER(6,2),
-- 	SENSOR_4 NUMBER(6,2),
-- 	SENSOR_5 NUMBER(6,2),
-- 	SENSOR_6 NUMBER(6,2),
-- 	SENSOR_7 NUMBER(6,2),
-- 	SENSOR_8 NUMBER(6,2),
-- 	SENSOR_9 NUMBER(6,2),
-- 	SENSOR_10 NUMBER(6,2),
-- 	SENSOR_11 NUMBER(6,2),
-- 	SENSOR_12 NUMBER(6,2)
-- );

-- create VIEW
CREATE OR REPLACE VIEW V_DP_IOT_1234 AS
SELECT SENSOR_ID, SENSOR_0 AS total_spent
FROM RAW_IOT
GROUP BY SENSOR_ID, SENSOR_0
ORDER BY SENSOR_ID DESC;


-- create DYNAMIC TABLE
CREATE OR REPLACE DYNAMIC TABLE DT_DP_IOT_1234
WAREHOUSE = md_test_wh_1
LAG = '60 minute'
AS
SELECT SENSOR_ID, SENSOR_0 AS total_spent
FROM RAW_IOT
GROUP BY SENSOR_ID, SENSOR_0
ORDER BY SENSOR_ID DESC;

DROP WAREHOUSE IF EXISTS md_test_wh_1;
