name: Update Local Repository and Run Sonar Scanner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-and-scan:
    runs-on: self-hosted
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      PROJECT_KEY: ${{ github.event.repository.name }}
      SONAR_BRANCH_NAME: ${{ github.ref_name }}
      SONAR_HOST: http://localhost:9000
      BASE_DIR: /Users/mdaeppen/workspace/Mother-of-all-Projects/local-github-process

    steps:
      - name: 📛 Show repository name
        run: echo "This repo is called $PROJECT_KEY"

      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🔄 Pull latest changes
        run: git pull

      - name: 🧪 Run Sonar Scanner
        run: |
          bash "$BASE_DIR/sonar-scanner_v1.sh"

      - name: ✅ Wait for Quality Gate to complete
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        with:
          scanMetadataReportFile: '.scannerwork/report-task.txt'

      - name: 📦 Zip source files
        run: |
          zip -r release.zip . -x '*.git*' '*.scannerwork*'

      - name: 🚀 Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.run_number }}
          tag_name: v${{ github.run_number }}
          files: release.zip
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ❄️ Run Snowflake Schema Cloning
        run: |
          bash "$BASE_DIR/snowflake-clone-db_v1.sh \
            --SOURCE_DATABASE=MD_TEST \
            --SOURCE_SCHEMA=IOT_REF_20250711 \
            --CLONE_DATABASE=MD_TEST \
            --CLONE_SCHEMA=I0T_CLONE_1"