name: Update Local Repository and Run Sonar Scanner

on:
  push:
    branches:
      - main  # Or your desired branch
  workflow_dispatch:

jobs:
  update-and-scan:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull latest changes
        run: git pull

      - name: Run Sonar Scanner
        run: bash /Users/mdaeppen/infra/sonar-scanner/bin/Mother-of-all-Projects.sh
