name: Update Local Repository and Run Sonar Scanner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-and-scan:
    runs-on: self-hosted
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      PROJECT_KEY: ${{ github.event.repository.name }}
      RELEASE_NUM: ${{ github.run_number }}
      SONAR_BRANCH_NAME: ${{ github.ref_name }}
      SONAR_HOST: http://sonarqube:9000
      SOURCE_DATABASE: MD_TEST
      SOURCE_SCHEMA: IOT_REF_20250711
      CLONE_DATABASE: MD_TEST
      CLONE_SCHEMA: IOT_CLONE
      SNOW_CONFIG_B64: ${{ secrets.SNOW_CONFIG_B64 }}
      SNOW_KEY_B64: ${{ secrets.SNOW_KEY_B64 }}

    steps:
      - name: 🔧 Set up dynamic base directories
        run: |
          echo "BASE_DIR_PROJECT=$HOME/workspace/${PROJECT_KEY}" >> $GITHUB_ENV

      - name: 📛 Show repo info
        run: |
          echo "📦 Project: $PROJECT_KEY"
          echo "🔀 Branch: $SONAR_BRANCH_NAME"
          echo "📌 Release #: $RELEASE_NUM"
          echo "🗂 BASE_DIR_PROJECT: $BASE_DIR_PROJECT"

      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔄 Pull latest changes
        run: git pull

      - name: 🧪 Run Sonar Scanner
        run: |
          bash /usr/local/bin/sonar-scanner_v2.sh

      - name: ✅ Wait for Quality Gate to complete
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        with:
          scanMetadataReportFile: '.scannerwork/report-task.txt'

      - name: 🔧 Set up github runner env
        run: |
          bash /usr/local/bin/github-runner_v1.sh

      - name: ❄️ Run Snowflake Schema Cloning
        run: |
          bash /usr/local/bin/snowflake-clone-db_v2.sh \
            --SOURCE_DATABASE=$SOURCE_DATABASE \
            --SOURCE_SCHEMA=$SOURCE_SCHEMA \
            --CLONE_DATABASE=$CLONE_DATABASE \
            --CLONE_SCHEMA=$CLONE_SCHEMA \
            --RELEASE_NUM=$RELEASE_NUM \
            --CONNECTION_NAME=$CONNECTION_NAME

      - name: 🏗️ Run Snowflake Deploy Structure
        run: |
          bash /usr/local/bin/snowflake-deploy-structure_v2.sh \
            --PROJECT_KEY=$PROJECT_KEY \
            --CLONE_DATABASE=$CLONE_DATABASE \
            --CLONE_SCHEMA=$CLONE_SCHEMA \
            --RELEASE_NUM=$RELEASE_NUM \
            --CONNECTION_NAME=$CONNECTION_NAME

      - name: 🔍 Run SQL Validation Tests
        run: |
          bash "$BASE_DIR_PROJECT/sqlunit/sql_validation_v2.sh" \
            --CLONE_DATABASE=$CLONE_DATABASE \
            --CLONE_SCHEMA=$CLONE_SCHEMA \
            --RELEASE_NUM=$RELEASE_NUM \
            --CONNECTION_NAME=$CONNECTION_NAME

      - name: 🧹 Drop Cloned Schema After Tests
        run: |
          bash /usr/local/bin/snowflake-drop-clone-db_v2.sh \
            --CLONE_DATABASE=$CLONE_DATABASE \
            --CLONE_SCHEMA=$CLONE_SCHEMA \
            --RELEASE_NUM=$RELEASE_NUM \
            --CONNECTION_NAME=$CONNECTION_NAME

      - name: 📦 Zip source files
        run: |
          zip -r release.zip . -x '*.git*' '*.scannerwork*'

      - name: 🚀 Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.run_number }}
          tag_name: v${{ github.run_number }}
          files: release.zip
          token: ${{ secrets.GITHUB_TOKEN }}
