name: Update Local Repository and Run Sonar Scanner

on:
  push:
    branches:
      - main  # Or your desired branch
  workflow_dispatch:

jobs:
  update-and-scan:
    runs-on: self-hosted
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      PROJECT_KEY_TEST: mother-project-marcel
      PROJECT_NAME: "Mother of all Projects"
      SONAR_HOST: http://localhost:9000
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull latest changes
        run: git pull

      - name: Run Sonar Scanner
        run: bash /Users/mdaeppen/infra/sonar-scanner/bin/Mother-of-all-Projects.sh
